Repository utopia-rise/godot-kotlin, pull requests merged in 2020-02, with the labels that each got.

#7 Change byte array size to 20 as it is max size of godot's variant
  tools/api-classes-generator/src/main/kotlin/ICall.kt
Labels: bug, client:macOS, host:macOS, tools:api-classes-generator

#8 Feature/receivers in property lambdas [Moved from old repo]
  API_DIFFERENCES.md
  samples/games/kotlin/src/main/kotlin/godot/samples/games/catchBall/Player.kt
  samples/games/kotlin/src/main/kotlin/godot/samples/games/dodge/Player.kt
  tools/api-classes-generator/src/main/kotlin/Class.kt
Labels: enhancement, need-rebase, tools:api-classes-generator

#15 Add missing plugin repository to samples and getting started guide
  GETTING_STARTED.md
  samples/coroutines/kotlin/build.gradle.kts
  samples/games/kotlin/build.gradle.kts
Labels: bug, documentation

#29 Feature/ios support
  .travis.yml
  .travis/deploy.sh
  COMPILING_FROM_SOURCE.md
  GETTING_STARTED.md
  samples/coroutines/kotlin/build.gradle.kts
  samples/games/kotlin/build.gradle.kts
  tools/annotations/build.gradle.kts
  wrapper/godot-library-extension/build.gradle.kts
  wrapper/godot-library/build.gradle.kts
Labels: 1.0.0, documentation, enhancement, feature, host:ios

#32 hotfix/add set to dictionary
  wrapper/godot-library/src/main/kotlin/godot/core/Dictionary.kt
  wrapper/godot-library/src/main/kotlin/godot/core/GDArray.kt
Labels: 1.0.0, bug, wrapper:godot-library

#35 Added selectable build target using -PbuildTarget=release
  COMPILING_FROM_SOURCE.md
  GETTING_STARTED.md
  samples/coroutines/kotlin/build.gradle.kts
  samples/games/kotlin/build.gradle.kts
Labels: 0.1.0-3.2, documentation, enhancement, samples:coroutines, samples:games

#40 Hotfix/fix travis ci deploy
  .travis/deploy.sh
  GETTING_STARTED.md
  buildSrc/src/main/kotlin/Dependencies.kt
  samples/games/kotlin/build.gradle.kts
  tools/annotations/build.gradle.kts
  tools/godot-annotation-processor/build.gradle.kts
  tools/godot-gradle-plugin/src/main/kotlin/org/godotengine/kotlin/gradleplugin/subplugin/KotlinGodotSubplugin.kt
  tools/kotlin-compiler-native-plugin/build.gradle.kts
  tools/kotlin-compiler-plugin/build.gradle.kts
  wrapper/godot-library-extension/build.gradle.kts
  wrapper/godot-library/build.gradle.kts
Labels: 0.1.0-3.2, bug

#46 Fix dependency resolution
  tools/entry-generator/build.gradle.kts
  tools/godot-annotation-processor/build.gradle.kts
Labels: bug

#47 Implement usage of newer gdnative apis
  wrapper/godot-library/src/main/c_interop/godot.def
  wrapper/godot-library/src/main/c_interop/registrations.h
  wrapper/godot-library/src/main/kotlin/godot/core/Dictionary.kt
Labels: bug

#48 Add the MpApt project to the projects we use section
  PROJECTS_WE_USE.md
  README.md
Labels: documentation

#43 Fix issues in game samples
  samples/games/Games/CatchBall/Scenes/Stage.tscn
  samples/games/Games/Dodge/Scenes/HUD.tscn
  samples/games/Games/Dodge/Scenes/Main.tscn
  samples/games/Games/Dodge/Scenes/Mob.tscn
  samples/games/Games/Dodge/Scenes/Player.tscn
  samples/games/Games/Pong/Scenes/Main.tscn
  samples/games/kotlin/src/main/kotlin/godot/samples/games/dodge/Player.kt
Labels: samples:games

#49 Fix entry generation tasks for projects with additional configurations
  GETTING_STARTED.md
  samples/games/kotlin/build.gradle.kts
  tools/godot-gradle-plugin/src/main/kotlin/org/godotengine/kotlin/gradleplugin/KotlinGodotPlugin.kt
  tools/godot-gradle-plugin/src/main/kotlin/org/godotengine/kotlin/gradleplugin/KotlinGodotTargetPreset.kt
Labels: 0.1.0-3.2, bug
